# -*- coding: utf-8 -*-
"""Data Visualization Pokemon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h3VdrLiglgAdk99j-xe20_QHvp9x6Dwx
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Pokemon.csv')
df.head()

"""# Visualization with pandas"""

df['Type 1'].value_counts().plot.bar()

df['HP'].value_counts().sort_index().plot.line()

viz = df['Speed'].plot.hist(
    figsize=(10,4),
    fontsize=10,
    bins=10,
    color='Red'
)
viz.set_title('Pokemon Speed Distribution', fontsize = 30)

df.plot.scatter(x = 'Attack' , y = 'Speed')

df.sample(300).plot.scatter(x = 'Attack' , y = 'Speed', figsize=(10,4), title = 'Attack vs Speed')

pokemon_generation = df.groupby(['Generation', 'Legendary']).agg({'Attack': 'mean', 'Defense' : 'mean'})
pokemon_generation

pokemon_generation.plot.bar(stacked=True)

pokemon_change = df.groupby('Generation').agg({'Attack': 'mean', 'Defense' : 'mean', 'Speed' : 'mean', 'HP' : 'mean'})

pokemon_change.plot.line()

"""# Visualization with matplotlib"""

count_pokemon = df['Type 1'].value_counts().reset_index()
count_pokemon

plt.bar(count_pokemon['Type 1'], count_pokemon['count'])
plt.xticks(rotation=90)
plt.xlabel('Type 1')
plt.ylabel('Count')
plt.title('Type 1 Distribution')

for i in range(len(count_pokemon)):
    plt.text(i, count_pokemon['count'][i] + 1, str(count_pokemon['count'][i]), ha='center')

plt.show()

plt.barh(count_pokemon['Type 1'], count_pokemon['count'], color='teal')
plt.xticks(rotation=90)
plt.xlabel('Type 1')
plt.ylabel('Count')
plt.title('Type 1 Distribution')
plt.show()

fig, ax = plt.subplots(2,1, figsize=(10,6))
df['Attack'].plot.hist(ax = ax[0], title = 'Pokemon Attack Distribution')
df['Defense'].plot.hist(ax = ax[1], title = 'Pokemon Defense Distribution')

"""# Visualization with seaborn"""

ax = sns.countplot(df, x='Type 1')

ax.set_xticklabels(ax.get_xticklabels(),rotation=90)
ax.set_title('Pokemon Distribution')
plt.show()

sns.histplot(df['HP'])

sns.jointplot(data=df, x = 'Attack' , y = 'Defense')

ax = sns.boxplot(data=df, x = 'Type 1', y = 'Attack')

ax.set_xticklabels(ax.get_xticklabels(), rotation= 90)

ax = sns.violinplot(data=df, x = 'Type 1', y = 'Attack')

ax.set_xticklabels(ax.get_xticklabels(), rotation= 90)

"""# Correlation"""

correlation_matrix = df.loc[:, ['HP', 'Attack', 'Defense', 'Speed' , 'Sp. Atk' , 'Sp. Def']].corr()

correlation_matrix

plt.figure(figsize=(10,8))
sns.heatmap(correlation_matrix, annot=True, cmap = 'coolwarm')
plt.show()